install.packages('dplyr')
install.packages('dygraphs')
install.packages('ggplot2')
install.packages('htmlwidgets')
install.packages('knitr')
install.packages('leaflet')
install.packages('mapproj')
install.packages('maptools')
install.packages('RColorBrewer')
install.packages('rgdal')
install.packages('rgeos')
install.packages('rmarkdown')

install.packages('shiny')
install.packages('shinyjs')
install.packages('SpatialEpi')
install.packages('spdep')
install.packages('xts')

