---
title: "rflexscan_test_data"
author: "qxa"
date: "3/10/2022"
output: html_document
---

```{r,include=FALSE}
library('rflexscan')
library("rgdal")
library("spdep")
library("RColorBrewer")
nys <- readOGR("data/NYS_Cancer/NYSCancer_region.shp",
                    stringsAsFactors = FALSE)

```

```{r}
head(nys@data[c("DOHREGION", "LATITUDE", "LONGITUDE",
                    "OBREAST", "EBREAST")])
```

```{r}
manhattan <- nys[startsWith(nys$DOHREGION, "36061"),]

coord <- data.frame(x=manhattan$LONGITUDE, y=manhattan$LATITUDE)
coordinates(coord) <- c("x", "y")
proj4string(coord) <- proj4string(manhattan)
coord <- spTransform(coord, CRS("+init=epsg:32618"))
nb <- poly2nb(manhattan, queen = T)
head(nb)

```

```{r}
fls <- rflexscan(name = manhattan$DOHREGION,
                     x = coord$x, y = coord$y, nb = nb,
                    observed = manhattan$OBREAST, expected = manhattan$EBREAST)
print(fls)
summary(fls)

plot(fls, rank = 1:7, col = brewer.pal(7, "RdYlBu"))
box()
legend("topleft", legend = 1:7, fill = brewer.pal(7, "RdYlBu"), bty="n")

choropleth(manhattan, fls, rank = 1:7, col = brewer.pal(7, "RdYlBu"))
legend("topleft", legend = 1:7, fill = brewer.pal(7, "RdYlBu"), bty="n")
```


```{r}
library(sqldf)
my_dat = read.csv2('data/prepared_dat.csv',sep = ',')

all_case = sqldf("select 地区编码 as DOHREGION, count(发病日期) as case_cnt,
                 经度 as lon, 纬度 as lat
                 from my_dat
                 where 经度 != ''
                 group by 地区编码
                 order by DOHREGION")

#get the neighbour of each district
#method: district are neighbours in the same province
i = 1
j = 1
nb = list()
while(i<=2490){
  province = substr(as.character(all_case$DOHREGION[i]),1,4)
  j = i
  cur_province = substr(as.character(all_case$DOHREGION[j]),1,4)
  while(cur_province==province & j<=2490){
    j = j+1
    cur_province = substr(as.character(all_case$DOHREGION[j]),1,4)
  }
 # print(j)
  for (k in seq(i,j-1)){
    if(k>i & k<j-1){
      cur_nb = c(seq(i,k-1),seq(k+1,j-1))
    }
    else if(k==i){
      cur_nb = seq(k+1,j-1)
     # print(seq(k+1,j-1))
    }
    else if(k==j-1){
      cur_nb = seq(i,j-2)
    }
    #print(cur_nb)
    nb = c(nb,list(cur_nb))
  }
  i = j
}

#sim ECASE
set.seed(311)
all_case$ECASE = all_case$case_cnt*runif(2490,0.1,2)


#prepare data type
all_case$lat = unlist(lapply(all_case$lat,as.numeric))
all_case$lon = unlist(lapply(all_case$lon,as.numeric))
all_case$DOHREGION = unlist(lapply(all_case$DOHREGION,as.character))
head(all_case)
```
```{r}
head(nb)
```

